# Generated by Django 5.1.1 on 2024-11-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('number', models.IntegerField(max_length=7)),
                ('grade', models.CharField(choices=[('9.8', '9.8'), ('9.6', '9.6')], max_length=4)),
                ('price', models.CharField(max_length=7)),
            ],
        ),
    ]
