# Generated by Django 5.1.1 on 2024-12-06 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comicapi', '0002_alter_comics_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comics',
            name='number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='comics',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
